CREATE TABLE IF NOT EXISTS user(
	user_id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(25) NOT NULL,
	password VARCHAR(25) NOT NULL,
	email VARCHAR(50) NOT NULL,
	discr VARCHAR(25) NOT NULL
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS student(
	user_id INTEGER,
	PRIMARY KEY(user_id),
	FOREIGN KEY(user_id) REFERENCES user(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	level INTEGER,
	name VARCHAR(20),
	surname VARCHAR(20),
	city VARCHAR(20),
	profession VARCHAR(20)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS professor(
	user_id INTEGER,
	PRIMARY KEY(user_id),
	FOREIGN KEY(user_id) REFERENCES user(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	level INTEGER,
	name VARCHAR(20),
	surname VARCHAR(20),
	city VARCHAR(20),
	profession VARCHAR(20)
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS admin(
	user_id INTEGER,
	PRIMARY KEY(user_id),
	FOREIGN KEY(user_id) REFERENCES user(user_id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS cours(
	cours_id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	level INTEGER NOT NULL,
	description TEXT NOT NULL,
	data TEXT NOT NULL,
	solutions VARCHAR(250) NOT NULL,
	name VARCHAR(50) NOT NULL,
	visible BOOLEAN NOT NULL,
	admin_user_id INTEGER,
	-- admin_id,manyToOne
	FOREIGN KEY(admin_user_id) REFERENCES admin(user_id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS cours_passed(
	student_user_id INTEGER,
	cours_id INTEGER,
	PRIMARY KEY(student_user_id,cours_id),
	FOREIGN KEY(student_user_id) REFERENCES student(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(cours_id) REFERENCES cours(cours_id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS text(
	text_id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	data TEXT NOT NULL
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS profs_students(
	student_user_id INTEGER,
	professor_user_id INTEGER,
	accepted TINYINT(1) NOT NULL,
	PRIMARY KEY(student_user_id,professor_user_id),
	FOREIGN KEY(student_user_id) REFERENCES student(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(professor_user_id) REFERENCES professor(user_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS communication(
	id_communication INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id_zero INTEGER NOT NULL,
	user_id_one INTEGER NOT NULL,
	UNIQUE unique_index(user_id_zero,user_id_one), 
	FOREIGN KEY(user_id_zero) REFERENCES user(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(user_id_one) REFERENCES user(user_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS message(
	id_communication INTEGER NOT NULL,
	sender INTEGER NOT NULL,
	data TEXT NOT NULL,
	time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id_communication, sender, time),
	FOREIGN KEY(id_communication) REFERENCES communication(id_communication) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;
